### ISSUE TITLE
水波纹花屏

### ISSUE THREAD

**Issue by ggggxiaolong** [lecymeng/EFI-8700K-AsusZ370I-UHD630#3]
你好，使用你的EFI文件驱动的黑苹果。其他的都驱动正常，核显也驱动了，硬件解码也正常。只有添加小工具的时候 水波纹的区域花屏。显示器使用的dp。你有没有这个问题？另外 10.15正式班已经发布了，可以直接更新吗？

**Comment by lecymeng** [comment]
我用的dp+4k屏没有花瓶问题，另外暂不打算升10.15，再过一个月再升吧~我这一套问题是 USB3 的速度显示的是 USB2的 480MBPS

**Comment by ggggxiaolong** [comment]
升级15.1了吗？

**Comment by ggggxiaolong** [comment]
Bios 需要特别设置吗

**Comment by lecymeng** [comment]
目前展示没升，因为15只支持64bit，BIOS 我只记得关闭安全启动，其他基本不需要改
